# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fb9e16d98ef2fd9650adedc60b6eeb2f"
application_url = "https://rodi-trip-planner-app.s2kt4t.easypanel.host"
embedded = true
name = "rodi-trip-planner"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_products,read_orders"

[app_proxy]
url = "https://rodi-trip-planner-app.s2kt4t.easypanel.host/apps/proxy"
prefix = "apps"
subpath = "trip-planner"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/create"
  topics = [ "customers/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/update"
  topics = [ "customers/update" ]

[auth]
redirect_urls = [ "https://rodi-trip-planner-app.s2kt4t.easypanel.host/api/auth" ]

[build]
automatically_update_urls_on_dev = true
