# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fb9e16d98ef2fd9650adedc60b6eeb2f"
application_url = "https://example.com"
embedded = true
name = "rodi-trip-planner"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[app_proxy]
url = "https://example.com/apps/proxy"
prefix = "apps"
subpath = "trip-planner"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
